### ISSUE TITLE
How to handle wipe resources ?

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#101]
Hi, as part of the security i'm using a token and i'm wiping all resources as recommended in the user guide :
service.invalidateConfiguration()
service.wipeResources()

So as marked in comments all resources receive a newData(.wiped) event but this one match newData so all my listeners try to unwrap nil. How to test if this new data isn't a "no data" ?

**Comment by Alex293** [comment]
eventCategoriesResource.addObserver(owner: self) {
            (resource, event) in
            if case .NewData(.Wipe) = event
            {
                eventCategoriesResource.load()
            }
            else if case .NewData = event
            {
                gEventCategories = resource.latestData!.typedContent(ifNone: [])
            }
            if case .Error = event
            {
                print("Error : \(resource.latestError?.userMessage)")
            }
}

It seams that this solve my issue but i have to add this test to each request so I'm sure there is a better way to handle this. If anyone have a better way to do it ?!

I'm pretty sure i'm missing something but if its the only way I suggest to move the wipe case to a new kind of event to make it clearer. Ex if case .Wiped = event

**Comment by pcantrell** [comment]
It seems like there are several separate problems entangled here:

**What to do when latestData is nil?**

There are many circumstances in which you’ll get a `resourceChanged()` notification with nil `latestData`:

- when you are added as a new observer of a not-yet-loaded resource (`ObserverAdded`), or
- when you are observing a not-yet-loaded resource and a new load request starts (`Requested`), or
- when that first load request is cancelled (`RequestCancelled`) or fails (`Error`), or
- when the resource is wiped (`NewData(Wipe)`).

Therefore you should _not_ be using `NewData(Wipe)` to detect when `latestData` is nil. Instead, it’s best to just ignore the `event` parameter and write your code to handle nil data whenever you see it.

In other words, get rid of the `!` in this code ([in most circumstances, you should avoid using ! in Swift](http://stackoverflow.com/questions/24018327/what-does-an-exclamation-mark-mean-in-the-swift-language/33399973#33399973)):

    gEventCategories = resource.latestData!.typedContent(ifNone: [])

…and instead do this:

    gEventCategories = resource.latestData?.typedContent(ifNone: [])

…or better yet, use Siesta’s shortcut:

    gEventCategories = resource.typedContent(ifNone: [])

…so that you _always_ get `[]` even if `latestData` is nil. Then your observer can look more like this:

    eventCategoriesResource.addObserver(owner: self)
        {
        [weak self] (resource, _) in

        // Always called. Write the would code so that it handles
        // gEventCategories being empty or having data.
        
        gEventCategories = resource.typedContent(ifNone: [])

        // Always called. Write showErrorMessage so that it clears
        // the error if message is nil.

        showErrorMessage(resource.latestError?.userMessage)
        }

Note the lack of conditionals.

**But who triggers the load?**

The most common approach is to call `resource.loadIfNeeded()` either in `viewWillAppear` or immediately upon observing a new resource.

In your case, though, it looks like you also want to trigger a refresh immediately on wipe. You could do this:

    eventCategoriesResource.addObserver(owner: self)
        {
        resource, _ in

        if resource.latestData == nil
            { resource.loadIfNeeded() }   // Note loadIfNeeded() instead of load() to prevent redundant requests
        }

…or, if you’d also like to automatically refresh the data when it gets stale, you could even do this:

    eventCategoriesResource.addObserver(owner: self)
        {
        resource, _ in
        resource.loadIfNeeded()
        }

You could even reuse that closure and attach it to lots of resources.

**OK, so what is the `event` parameter for, then?**

It’s primarily for optimization when UI updates are expensive — but they rarely are, so in most circumstances, the right approach is to first get your code working _without_ examining `event`, then optimize only when you’re proved you have a performance problem.

The [events section in the user guide](http://bustoutsolutions.github.io/siesta/guide/observers/#resource-events) explains this in more depth. And as that section says, a lot of branching on `event` is a code smell in Siesta apps.

Let me know if this answers your question.

**Comment by Alex293** [comment]
Awesome ; just what I wanted ! Thank you for these explanations. It is clear to me now.
