### ISSUE TITLE
ResourceStatusOverlay not found

### ISSUE THREAD

**Issue by beniaminorossini** [bustoutsolutions/siesta#108]
As subject, i can't find ResourceStatusOverlay anywhere in my project (Siesta 1.0 beta10 correctly installed and working).

Thx

**Comment by beniaminorossini** [comment]
Ok, i understand that few days ago you have splitted siesta and siestaui, but i not understand how to install the UI part.

You can help me?

Thx

**Comment by Aciid** [comment]
subscribing

**Comment by pcantrell** [comment]
It depends on whether you are using CocoaPods, Carthage, or a manual build. Please see the instructions under “Breaking Changes” in the release notes for beta 10:

https://github.com/bustoutsolutions/siesta/releases

Prompted by this question, I’ve updated the README to include these instructions as well:

https://github.com/bustoutsolutions/siesta#installation

Try that and let me know how it works for you.

**Comment by beniaminorossini** [comment]
@pcantrell It was cocoapods. 
On https://cocoapods.org i've not found anything, not Siesta nor SiestaUI, very strange don't you?
Anyway, thank you so much for readme update.

**Comment by pcantrell** [comment]
CocoaPods does t show prerelease/beta in its search results, even if there is not a 1.0 release yet. An unfortunate shortcoming. But there is a Siesta page on the site: http://cocoapods.org/pods/Siesta

Do let me know if you get it working so that we can close this issue.

**Comment by beniaminorossini** [comment]
Yeah, the repo is ok and i've loaded UI components in my projects.
I have a little problem with the ResourceStatusOverlay: i've followed basic instruction on readme but i missed what i have to do in interface builder.

'''@IBOutlet weak var statusOverlay: ResourceStatusOverlay!'''

must be linked to which IB component? A simple view?

**Comment by Aciid** [comment]
@pcantrell upgraded from b 9 to b 10 using instructions provided everything works without a hitch.
It was just unclear since the readme's and samples were not up to date. I didn't understand from the pod file nor the commits that the UI was branched.

Thanks!

**Comment by pcantrell** [comment]
Glad it’s working!

The simplest quick and dirty way to get a status overlay into your view hierarchy is the way the example project does it: leave it out of your storyboard altogether, [instantiate it directly in code](https://github.com/bustoutsolutions/siesta/blob/1.0-beta.10/Examples/GithubBrowser/Source/UI/RepositoryListViewController.swift#L25), and then use [`embedIn`](https://github.com/bustoutsolutions/siesta/blob/1.0-beta.10/Examples/GithubBrowser/Source/UI/RepositoryListViewController.swift#L40) and [`positionToCoverParent`](https://github.com/bustoutsolutions/siesta/blob/1.0-beta.10/Examples/GithubBrowser/Source/UI/RepositoryListViewController.swift#L43-L45) to add it to your view hierarchy.

The reason to do this:

    @IBOutlet weak var statusOverlay: ResourceStatusOverlay!

…is if you want to customize the overlay with your own look & feel instead of the default baked-in one. To make that work, add a generic `UIView` in your storyboard and then give it a custom class of `ResourceStatusOverlay`:

<img width="262" alt="screen shot 2016-09-06 at 9 17 44 pm" src="https://cloud.githubusercontent.com/assets/378162/18297603/794080f6-7477-11e6-8574-6353db0f49c0.png">

Note that the module name would be `SiestaUI` if you’re building with Carthage.
