### ISSUE TITLE
Minimum OS set to 9 for Swift 3 

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#111]
With the update to Swift 3, you updated the minimum OS version to iOS 9.  I understand that this practice is promoted by Apple, but it seriously jeopardizes our ability to use Siesta in our app.  Of our apps 10.5 K monthly active users, 10% of them are on iOS 8.  Since these users are the members of libraries which in turn are my company's customers, we have pretty much no leverage to tell them they have to update their devices.  We really can't drop iOS 8 without a compelling technical rational.  Is there such a rational?

**Comment by pcantrell** [comment]
I was getting weird runtime errors about missing symbols from the platform libs when tried to run on iOS 8, and wanted to get something working for the majority of users out there.

I’d _love_ some assistance getting it to run on iOS 8. Would you be willing to poke at it a bit and see what happens if you change Siesta to target it?

**Comment by jordanpwood** [comment]
I'll give it a poke, see what happens.

**Comment by pcantrell** [comment]
As I look back at that error message, one extra bit of info that might be super helpful: the errors I saw were when I tried to run tests on an 8.x simulator, and it looks like they happened when it tried to load the Alamofire framework — which just dropped 8.x support.

The tests test the optional Alamofire integration, but of course Siesta doesn’t require AF. It’s quite possible that Siesta itself will support 8.x just fine, and it’s only the tests that bomb.

Let me know what you find!
