### ISSUE TITLE
What are similarities and differences between siesta and moya?

### ISSUE THREAD

**Issue by rlam3** [bustoutsolutions/siesta#128]
What are similarities and differences between siesta and moya?
Any trade offs? 
Does siesta support rxswift? 
How does siesta handle with JWT based authentication and requests? 

New to siesta. Thanks!

**Comment by Alex293** [comment]
Hi I'm not expert with siesta and I don't know moya.
There is an extension for reactiveCocoa and it's very shortly written so proving this to rx should be easy.
I use JWT with siesta, tokens are not in the heart of Siesta but are easy to integrate with. Look at the sample in the user doc and in the closed questions there are samples with token.

You should definitely give Siesta a try :)

**Comment by pcantrell** [comment]
The README has a [comparison with other frameworks](https://bustoutsolutions.github.io/siesta/#comparison-with-other-frameworks), including Moya.

Siesta does not contain special support for JWT, but has a robust configuration mechanism that lets you provide transparent authentication for a wide variety of approaches. See [this section of the User Guide](http://bustoutsolutions.github.io/siesta/guide/configuration/#decorating-requests-via-configuration).

It’s straightforward to wire a `Resource` or a `Request` up to RX. The included ReactiveCocoa extension is a good starting point. There’s no RX extension for it included with Siesta, because nobody has submitted a pull request for one yet!
