### ISSUE TITLE
RequestChain not repeatable

### ISSUE THREAD

**Issue by jwardle** [bustoutsolutions/siesta#130]
Depending upon Service configuration it appears a `resource.load()` can result in a `RequestChain` being returned instead of a standard `NetworkRequest`.

If this request chain fails for some reason then it would be desirable to be able to `requestChain.repeated()` the `RequestChain`... however the previous `wrappedRequest` state is not cleared when the repeated `RequestChain` is created (i.e. the request's `self.networking` is still set from the original attempt to fulfil the request) - therefore attempting to call `repeatedChain.start()` results in an "already started" message, and no attempt to repeat the request over the network. 

With `wrappedRequest` being a private variable - it is also not possible to recreate the request/chain with a reset internal state.

**Comment by pcantrell** [comment]
This is a good point: it does seem like a `RequestChain` should repeat the underlying request.

I’d like to drive this out with a use case or two if possible. Can you provide a sketch of what you’re doing?

**Comment by jwardle** [comment]
All I am trying to to is react to a failed request (say server returns 500 error, or a network erro) by repeating the initial request. Normally in reaction to a "Tapp here to retry" type button.

1. Create request
2. Request is wrapped by a RequestChain, as I have configuration which chains the request to handle auth access token renewal etc.
3. Request is sent & fails.
4. User wants to retry the request - tapping retry button
5. Repeated RequestChain is created and executed
6. Retry fails as wrapped request has already been 'started'

**Comment by pcantrell** [comment]
OK, thanks for the use case! That is helpful. Rethinking my thinking on this, you’re spot on: the current behavior is incorrect. I’ll get a fix together, and ping you for a sanity check when it’s ready.

---

A side note on implementing “tap to retry” behavior, which you likely already know, but just in case it’s useful to you or any others reading: `req.repeated()` does _not_ call `req`’s callback hooks a second time. In other words:

```swift
let request = resource.request(.post)
request.onCompletion { _ in print("hello") }
request.repeated().start()  // will _not_ say "hello" a second time
```

This is by design: the contract of `Request` is that it is a thing that happens exactly once, and has a single outcome that never changes once the request is done. Hooks can and should rely on the fact they they can be called at most once. (Look at #132, for example: repeating already-called hooks would cause `requestCount` to go negative.)

Be careful! This:

```swift
let req0 = resource.load()
let req1 = resource.load()
```

…is _not_ the same as this:

```swift
let req0 = resource.load()  // request has hooks that update resource state
let req1 = req0.repeated()  // repeated request has no hooks
req1.start()
```

The latter example will _not_ update the resource state. For that reason, you’ll usually want to implement “tap to retry” by calling `resource.load()` again, as `ResourceStatusOverlay` does. If you’re implementing tap to retry for mutating request (POST etc.), then you’ll probably want to pass around some kind of “make request and handle results” closure that you call twice instead of using `repeated()`.

(The primary purpose of `repeated()` is to exist inside a request chain, for doing retries before any hooks get called. Note that inside a chain, the problem above doesn’t exist because hooks attached to the whole chain don’t get called until the chain declares itself done. In other words, the whole chain appears to be a single request. The different with “tap to retry” is that you can see a request fail, and you want to then see a different second outcome. Second outcome implies second request implies attaching hooks again.)

**Comment by pcantrell** [comment]
@jwardle: If you have a minute, would you mind testing #134 and see if it gives the behavior you expect?

**Comment by jwardle** [comment]
@pcantrell: this issue appears to be fixed! Thanks!

**Comment by jwardle** [comment]
I was attempting to create a reusable 'loading more' implementation using repeated(), however will review he above commentary to see if there is a better resource-centric method given my requirements!
