### ISSUE TITLE
RemoteImageView rendering mode

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#131]
Hi i'm playing with RemoteImageView and as it get its image from the net choosing the rendering mode can be useful. I've added a quick fix for it and it works : 

in class RemoteImageView add : 

``` swift
public var renderingMode : UIImageRenderingMode?
```

and in updateViews() replace : 

``` swift
image = imageResource?.typedContent(ifNone: placeholderImage)
```

by : 

``` swift
if let renderingMode = renderingMode
{
    image = imageResource?.typedContent(ifNone: placeholderImage)?.withRenderingMode(renderingMode)
} else {
    image = imageResource?.typedContent(ifNone: placeholderImage)
}
```

This is a quick draw, there may be a better way to do it ?

**Comment by pcantrell** [comment]
You could configure `withRenderingMode(…)` as a transformer at the service level, but I tend to agree that this would be a good thing to be able to include independently on each image view.

There are other `UIImage` methods it seems like people might also want to apply to the downloaded image, such as `resizableImage(withCapInsets:)` and `imageFlippedForRightToLeftLayoutDirection()`. Instead of duplicating portions of the `UIImage` API for each one, `RemoteImageView` could provide a custom transform-on-set closure:

```swift
public var imageTransform: (UIImage?) -> UIImage? = { $0 }
```
```swift
image = imageTransform(imageResource?.typedContent(ifNone: placeholderImage))
```

…and then you’d do:

```swift
someImageView.imageTransform = { $0?.withRenderingMode(.alwaysTemplate) }
```

How would you feel about that?

**Comment by Alex293** [comment]
Indeed that would be very convenient !

**Comment by pcantrell** [comment]
Good, let’s do it. I’m keeping new functionality frozen until the imminent 1.0 release is out the door. (Very soon!) Once it’s done, this easy fix can go in the first follow-up release.

**Comment by Alex293** [comment]
I've tested this in my project this is perfect

**Comment by pcantrell** [comment]
1.0 is out. Feel free to submit a PR for this.
