### ISSUE TITLE
RemoteImageView loader

### ISSUE THREAD

**Issue by Alex293** [bustoutsolutions/siesta#133]
What you be the preferred way to add a loading indicator over every RemoteImageView ?

**Comment by pcantrell** [comment]
There’s a `loadingView` property which you point at a loading indicator.

You’ll typically want to add the loading indicator to your layout and bind it when setting up your view hierarchy. (Because `loadingView` is an IBOutlet, you can do this in a storyboard with no additional code.)

You can also subclass `RemoteImageView` to create the indicator you desire and set the property on view creation.

**Comment by pcantrell** [comment]
@Alex293: Did this answer your quest? I’m closing this issue, but feel free to reopen it if you find a bug or feature request that’s stopping you from getting it working.
