### ISSUE TITLE
SwiftyJsonTransformer won't work on normal .request().onSuccess()

### ISSUE THREAD

**Issue by aescarcha** [bustoutsolutions/siesta#137]
Hi, first of all great work :) this is amazing.

Now, I'm trying your framework on Swift3, but I have an issue I've been trying to solve for hours

I implemented token login and it worked, but now I'm setting up transformers and it died...

Before it was: 

    @discardableResult func createNewAuthToken(username: String, password: String) -> Request{
        return self.token.request(.post, json: ["username": username, "password": password, "grant_type": "password", "client_id": self.clientId, "client_secret": self.clientSecret ])
            .onSuccess() { response in
                if(response.jsonDict["access_token"] != nil){
                    self.authToken = "Bearer "
                    self.authToken += response.jsonDict["access_token"] as? String ?? self.authToken
                }
                self.invalidateConfiguration()              // …make future requests use it
            }
    }

Now I added SwiftyJSONTransformer as it is on the demo project

    private let SwiftyJSONTransformer =
        ResponseContentTransformer
            {
                JSON($0.content as AnyObject)
            }

And my init

    public init(baseURL: String) {
        super.init(baseURL: baseURL)
        self.configureTransformers()

        configure("**", description: "All") {
            $0.pipeline[.parsing].add(self.SwiftyJSONTransformer, contentTypes: ["*/json"])
            $0.headers["Authorization"] = self.authToken
            $0.decorateRequests {
                self.refreshTokenOnAuthFailure(request: $1)
            }
        }
    }

But when I want to get the `access_token` from the response, I can't do a `response["access_token"]` as I'd expect from a SwiftyJson object, and `response.jsonDict` is empty. What am I doing wrong?

**Comment by pcantrell** [comment]
You can’t do `response["access_token"]` because `response` is an `Entity` object. It is `response.content` that contains the transformed content — and _that_ is what will be `JSON` if you configure your pipeline to make it so.

To use the `JSON`, you’ll need to do one of the following:

1. Downcast it manually:
```swift
(response.content as? JSON)?["access_token"].string
```
2. Use Siesta’s `typedContent()` helper:
```swift
let json: JSON? = response.typedContent()  // if you want nil for no content
let json: JSON = response.typedContent(ifNone: JSON([:]))  // if you want empty JSON for no content
```
3. Add your own convenience accessor so you don’t have to do that cast all over the place:
```swift
extension TypedContentAccessors {
    public var json: JSON {
        return typedContent(ifNone: JSON([:]))
    }
}
```
…which then lets you do:
```swift
response.json  // tries to cast response to JSON
```
Option 3 is exactly how the built-in `jsonDict`, `text`, etc. all work.

> `response.jsonDict` is empty

That happens because `jsonDict` is looking for a dictionary, but the content is now `JSON` and not a dict.

> Hi, first of all great work :) this is amazing.

Thanks! Please help spread the word.

**Comment by aescarcha** [comment]
Ty very much, this solved my problem and some issues that followed :)
