### ISSUE TITLE
Appending a path to a resource

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#160]
Hi Paul,
I'm trying to append a path to my service so that i make a request, but i have noticed that it is converting my characters.
Here is my example, 
my service class has a base url of:
> https://supercoolserver.com/special-service

In my code i do something like so:

`let service = Service(baseURL:"https://supercoolserver.com/special-service")`

Then i want to call the special service's path method with the user id, in this case it would like this
> /1234567/do-stuff?timeframe=5

The full url would be

> https://supercoolserver.com/special-service/1234567/do-stuff?timeframe=5

In code, i perform:

`service .resource("/1234567/do-stuff?timeframe=5")`

But when the request is made i can see in the log its

> https://supercoolserver.com/special-service/1234567/do-stuff%3Ftimeframe=5

Is there something I'm doing wrong? I checked the documentation and laughed at your joke about the greyhound terminal. In the documentation, there is a note that says

> The `path` parameter is simply appended to `baseURL`’s path, and is _never_ interpreted as a URL. Strings such as `..`, `//`, `?`, and `https:` have no special meaning; they go directly into the resulting resource’s path, with escaping if necessary.

So i would assume it should'nt be encoding the ?

**Comment by Alex293** [comment]
Use .withParam() to add a GET parameter.
Use .child() to add a path component.

Ex : service.resource("/1234567"/do-stuff).withParameter("timeframe", 5)

**Comment by Reedyuk** [comment]
hmm, is there anyway that i could just pass the string in, and siesta interpret it as formatted?
The reason being, i created a network adapter around my code and i don't want to have to either handle individual params, or directly call additional methods when there is parameters.

**Comment by Alex293** [comment]
Your adapter could just chain a withParameter in a for loop. Otherwise there is a way to create a resource directly from url look for something like resource(withUrl ). I don't remember the actual way to do it but I think it's in the quick start doc

**Comment by pcantrell** [comment]
@Alex293 is right. The `resource(_:)`, `resource(baseURL:path:)`, `child(…)`, and `withParam(…)` methods are all specifically designed _never_ to let path parameters bleed into query strings or vice verse, and never to let parameters escape outside of the service’s `baseURL`. This is a security feature, so that you can do things like `resource("/items").child(itemID)` where `itemID` is potentially malicious user input.

Relative URL handling does not have this protection. It resolves relative URLs much like a browser does, and lets you freely modify the path, query string, and host, or even provide a new absolute URL altogether. This is meant for data that you’ve generated and sanitized yourself, or that was sent from the server.

For you purposes, you could do:

```swift
let root = service.resource("/")
root.relative("./1234567/do-stuff?timeframe=5")  // note the leading dot
```

If you are using relative and absolute URLs with Siesta, consider using one of the approaches described in the [Host Whitelisting](http://bustoutsolutions.github.io/siesta/guide/security/#host-whitelisting) section of the user guide.

**Comment by Reedyuk** [comment]
Great, for now i will take Pauls approach, but when i get time, i will write a method to add the parameters correctly.
