### ISSUE TITLE
WrongInputTypeInTranformerPipeline

### ISSUE THREAD

**Issue by BilalReffas** [bustoutsolutions/siesta#168]
I'm receiving this issue : 

> RequestError(userMessage: "Cannot parse server response", httpStatusCode: nil, entity: nil, cause: Optional(Siesta.RequestError.Cause.WrongInputTypeInTranformerPipeline(expectedType: Swift.Dictionary<Swift.String, Any>, actualType: __NSSingleObjectArrayI, transformer: Dictionary<String, Any> → Luubra)), timestamp: 505942172.980878)

I 'm using `Unbox` to parse the JSON

```swift
   self.configureTransformer("users/*/luubras",
                        requestMethods: [.get, .post, .delete],
                         atStage: .model,
                         description: "Luubra parsing",
                         contentTransform: { try unbox(dictionary: $0.content, atKey: "luubras") as [Luubra] })
```

In my ViewController I set the Observer 

```swift
       API.luubras.addObserver(owner: self) { [weak self] resource, _ in
            self?.luubras = resource.latestData?.typedContent() ?? []
            if let error = resource.latestError {
                print(error)
            }
        }
```

Thank you for your help :)

**Comment by pcantrell** [comment]
The key info in that error message is here:

```
expectedType: Swift.Dictionary<Swift.String, Any>
actualType: __NSSingleObjectArrayI
```

Your transformer expects a dictionary, but it’s getting an Array.

Why does it expect a dictionary? Because the first arg to `unbox(dictionary:…)` is a dictionary, so `unbox(dictionary: $0.content, …)` means the transformer’s input has to be a dictionary.

Why is it getting an array? Presumably because the API returned one, i.e. the JSON the server sent was `[…]` instead of `{…}`.

**Comment by BilalReffas** [comment]
Okay awesome thank you for your fast reply :)
