### ISSUE TITLE
Specify queue on which resourceChanged to be called

### ISSUE THREAD

**Issue by richardtop** [bustoutsolutions/siesta#175]
Currently I was not able to find an option to specify on which thread `resourceChanged` to be received.
Such option would allow more flexibility when dealing with big responses.

**Comment by pcantrell** [comment]
Siesta follow the UIKit convention that any time you are looking at shared state — like a `Resource` — you should do it only from the main thread. All observers and callbacks are therefore called on the main thread, and this is not configurable.

If your `resourceChanged` is consuming significant CPU time for big responses, that’s a bad code smell. Two possible resolutions:

- If you’re doing intensive processing of a response that all subscribers to that resource will want (e.g. parsing), put that in Siesta’s transformer pipeline, which _does_ run off the main thread.
- Otherwise, use `resourceChanged` to grab a snapshot of the relevant resource state (your resources do use immutable content, right?), and then spawn a concurrent task using GCD (takes one extra line!) or whatever concurrency approach makes sense for your app.

**Comment by pcantrell** [comment]
P.S. Feel free to reopen this if you have a specific, concrete problem that Siesta’s thread model prevents you from solving.

**Comment by richardtop** [comment]
@pcantrell the problem is that I am trying to use Realm for data persistence. When the new resource arrives, the appropriate controller saves models in Realm and then gives these models to the ViewController. If there is no network connectivity, the controller just returns saved models.

Realm concurrency model requires re-fetching or re-creating models on each thread, so I can't just pass them around the threads. Data persistence should happen on the same thread the models were mapped. So, as I don't know the thread resources has been created on, I can't just use GCD to make a new one (e.g. what if thread changes in next version of Siesta?). 

Such a convention makes it difficult to combine the framework with other tools. 
I can't really see now, how can I embed object persistence in pipeline.
What I'm really looking into is very simple app configuration. In previous version of the app I've used RestKit + CoreData and it worked awesome.
Now, it's time for a new version in Swift, so what I'm looking into is something like this:
(REST Resource) -> <Store In DB> -> <Fetch from DB> -> <UI>
If the app goes offline, it just fetches latest data from the DB. When the app is online, it first, fetches old data, updates it, and then refetches the new data from db.

That was the reason I decided to try Siesta in the first place - I looked for something simple to make this app quickly.

**Comment by Alex293** [comment]
There are some closed issues about making an extension for Realm and a piece of code on the net. 

Altho I don't know the status of this but I'm interested in doing the same thing. As of now I didn't dived into developing the extension as I'm still building my app and improving my swift skills but I'd be glad to try to help if you start an extension.

**Comment by Alex293** [comment]
Also as in Siesta Res and Res.child(id) is not the same resource you will need to add someway to link those two resource if you want to really benefit from using Realm as the cache for Siesta. Otherwise Realm would just give you persistent for Siesta but you would loose the Search Backlinks etc links or things like this. 

Well I not completely sure about that and I may have missed something but that what I came to while try to play around Realm with Siesta

**Comment by pcantrell** [comment]
If you just want offline access, then what you are looking for is [`EntityCache`](http://bustoutsolutions.github.io/siesta/api/Protocols/EntityCache.html). Note its `workQueue` property, which is there specifically to support Realm models. Also note that recent Realm versions let you pass models across threads, IIRC.

As @Alex293 points out, there are some concerns about mixing Realm and Siesta. The fundamental problem is that _both_ can act as an observable cache, and so you end up with two versions of your data competing for canonicity, one in the shape of an API (Siesta) and one in the shape of a database (Realm). Some of the implications:

- If your app observes Realm models instead of Siesta resources, you lose all the benefits of resource state metadata like `isLoading` and `latestError` and the associated transition events.
- If your app observes Siesta resources, then you lose the benefits of using Realm queries — or at least of knowing when their results change.
- If your app modifies Realm data locally but observes Siesta resources, you'll have to back-map those modifications to Siesta’s in-memory cache.

As you describe your project’s problem, it sounds like you could use Realm only as a backing store for `EntityCache`, and have the rest of your app take a Siesta-shaped view of the world. But there’s really not a one size fits all answer here..

**Comment by richardtop** [comment]
@pcantrell it seems that it is the solution I'm looking into.
However, I have one more question, let's say, I have a Realm entity with such values:
```
var ValueThatHasOnlineRepresentation
var ValueThatIsStoredOnlyOnDevice
```
So, during the next update cycle, the app should update only `online` values and keep `offline` values the same, while also deleting orphaned objects.
So this is a little bit different than just `EntityCache`.

**Comment by couchdeveloper** [comment]
> Siesta follows the UIKit convention that any time you are looking at shared state — like a Resource — you should do it only from the main thread. All observers and callbacks are therefore called on the main thread, and this is not configurable. See the Threading chapter of the user guide.

I am currently evaluating Siesta, and I'm very excited. However, what I am not so satisfied with is the current approach of Thread Confinement - even worse, confined to the Main Thread.

IMHO, there is absolute no reason to restrict ourself to this threading model. It may require us to extra dispatch from and to the main thread, back and force - if necessary. This is at least suboptimal. It even might go worse, if the client code makes no assumptions about the thread where callbacks coming in, which can lead to deadlocks, stutter on the UI, and it performs suboptimal.

If we were able to specify an execution context (aka dispatch queue) for a service, where all internal synchronisation takes place and additionally, would let us specify a queue where callbacks will be called, we would gain a lot! This could make the API completely agnostic about the calling thread (== thread safe) - and more complex asynchronous systems of network requests that call "load a resource" on any thread, could be implemented more easily.

**Comment by pcantrell** [comment]
Yes, I’ve investigated a model where a service must be used only on the thread on which it was created. This turns out to be a fairly intrusive change, and I haven’t (yet) included it because there’s not good evidence that this intrusion is justified by performance gains. People do periodically worry about performance in theory, but then AFAIK consistently find that it’s not a problem in practice.

---

It is worth noting that Siesta is not confined to the main thread; only _shared state_ operations are. With one exception[1], everything expensive happens on background queues, and Siesta takes pains to ensure that operations that remain on the main thread are fast — on the order of microseconds fast.

This model matches actual usage quite well: expensive processing of response data happens in the pipeline (and thus off the main thread), I/O happens in the cache (and thus off the main thread), and the calls that remain are usually either triggered by or directly cause UIKit work, so thread hopping would be an unnecessary expense.

You’re concerned about suboptimal performance and UI jank, as well you should be! Take a look at the included example app, for example, in which _every cell in the table views_ contains multiple `ResourceObserver`s (one for the data and one for the image), yet tables still scroll smoothly.

This is why Siesta hasn’t yet implemented the feature you’re asking for: it adds complexity to an intentionally simple CodeBase, and there is not good evidence – at least not yet — that this complexity is justified by performance gains. If you or anyone does have good empirical evidence that there’s a performance problem here to solve, I would certainly consider including a more flexible thread model.

---

One clarification:

> if the client code makes no assumptions about the thread where callbacks coming in

In the current model, client code should assume callbacks always come on the main thread, and bounce to another thread if something expensive is going to happen. Client code thus does not need to “make no assumptions.”

---

[1] The exception is encoding large request bodies. This is an important piece of future work.

**Comment by couchdeveloper** [comment]
Hi Paul 
thank you for the reply.

I agree, the dispatching to the main thread, and back and force occasionally, is hardly noticeable in many scenarios in practice. However, as you pointed out already, Siesta makes the assumption that observer callbacks will always go straight to UIKit - but there are scenarios where this is not the case and solutions become unnecessary cumbersome. 

For example, in my application the observer is a View Model (in MVVM) - not a View Controller - and it may take one or more steps to apply transformations to the source model coming out of the network layer. This is logic which does not fit well in the pipeline concept - albeit, this is awesome. The point is, this logic does not belong to the network layer, it's more like business logic. I want to keep the View Model as much as possible decoupled from the network layer - even though, there are inevitable dependencies. It should be possible to use another network layer without changing too much in the View Models. The transformation applied to the model can be executed on non-main threads.

Well, the good message is: there's no reason to make this assumption aka restriction. We can use any thread to call callbacks and we can use any synchronisation approach for internal shared state, completely decoupled and completely private for the client.  We can also make the resource available only from within arguments in callbacks, thus making them automatically synchronised when passing it from internal to external on what ever execution context the callback will be called on. After a client safely receives the resource, it can dispatch to any other execution context to satisfy his needs for synchronisation.

The best we can choose from an execution context is a "private execution context", more precisely a global dispatch queue with default QoS. Optionally, we can let the caller pass in a parameter where the callbacks should be called. This yields the fasted code, but the more important aspect here is, that the callback code looks much nicer without all the dispatch dance back and force and thus is also far less error prone.

On the other hand dispatching a callback using a "well-known thread" - and there is only one, the _main thread_ - is the most error prone. It's some sort of "responsibility inversion": the framework takes the responsibility of choosing the execution context on behalf of the client that defines the callback.


Perhaps, I might as well start with a PR, instead of too much talking, so we can see how that would look like ;).  What do you think about this?
