### ISSUE TITLE
Accepting a plain string as a response

### ISSUE THREAD

**Issue by nabbestemmia** [bustoutsolutions/siesta#176]
Hello. 
I'm very happy of using siesta in my swift built application. 
But I need a little help for dealing with a legacy service. This service returns me a plain "true" string in case of positive outcome. But because of this, I'm getting the sequent error:
▿ ResponseInfo
  ▿ response : Error(userMessage: "Cannot parse server response", httpStatusCode: nil, entity: nil, cause: Optional(Siesta.Error.Cause.JSONResponseIsNotDictionaryOrArray(actualType: "__NSCFBoolean")), timestamp: 507553809.87161499)
    ▿ Failure : Error
      - userMessage : "Cannot parse server response"
      - httpStatusCode : nil
      - entity : nil
      ▿ cause : Optional<ErrorType>
        ▿ Some : JSONResponseIsNotDictionaryOrArray
          - actualType : "__NSCFBoolean"
      - timestamp : 507553809.87161499
   - isNew : true

Is there a way to configure my  Service, in order to prevent errors in cases like this?
Thank you very much for your work!

**Comment by pcantrell** [comment]
You can remove default parsing and apply Siesta’s string transformer if you want to parse all responses for a resource as strings. (See the Pipeline section of the user guide.)

In your case, however, where a JSON service is returning a bare JSON literal instead of a dictionary or array, there's a non-obvious but simple solution described here:

https://github.com/bustoutsolutions/siesta/issues/150

In your case, you want to tell Siesta to consider bare booleans to be valid JSON values:

    extension Bool: Siesta.JSONConvertible { }

(The `Siesta.` is just for clarity.)

This should fix your problem. Feel free to reopen this issue if it doesn’t.

**Comment by nabbestemmia** [comment]
I'll try asap and let you know. For the time being, thank you so much!
