### ISSUE TITLE
Cannot use self signed server

### ISSUE THREAD

**Issue by nabbestemmia** [bustoutsolutions/siesta#191]
Hello Siesta Team!
I need to connect to a test server for my app, which has a self signed certificate. But I keep getting an error, saying "The certificate for this server is invalid"  etc. etc.
How can I configure my client to ignore untrusted servers? I even setted my info.plist in order to accept everything but it still doesn't work

**Comment by pcantrell** [comment]
Siesta doesn't deal with certificate validation at all. This is something that the underlying network layer handles. That mean you’ll need to debug the problem at that level: either URLSession (aka NSURLSession, the Siesta default) or Alamofire if you’re configuring Siesta to use it instead. [This Stack Overflow question](http://stackoverflow.com/questions/19507207/how-do-i-accept-a-self-signed-ssl-certificate-using-ios-7s-nsurlsession-and-its) might be helpful, for example.

Once you have a `URLSessionConfiguration` that properly ignore the self-signed certificates, you can pass it as the `networking:` parameter when you create your Siesta `Service`.

P.S. You might gently suggest to your test team that they use Let’s Encrypt instead of a self-signed cert. Less danger of “insecure by accident” that way!

**Comment by rauanmayemir** [comment]
I'm not sure if you can use letsencrypt for local domains.
Anyway, this is how I resolved the issue for Alamofire:
```
let sessionManager: SessionManager = {
  let serverTrustPolicies: [String: ServerTrustPolicy] = [
      "mydomain.local": .disableEvaluation,
      "192.168.1.100": .disableEvaluation
  ]

  let configuration = URLSessionConfiguration.default
  configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders

  return SessionManager(
      configuration: configuration,
      serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
  )
}()
```
In your Service:
```
class ApiService: Service {
// ...
  init() {
    super.init(
      baseURL: "http://yourbaseurl", networking: sessionManager
    )
    // ...
  }
```

**Comment by pcantrell** [comment]
That's very nice! You're right, I doubt that Let's Encrypt handles local domains — but limiting the server trust to specific hosts as you're doing reduces the risk of it causing a vulnerability. Thanks for sharing your nice code.

**Comment by nabbestemmia** [comment]
Unfortunately, the test server of the company I work for is "untouchable", because life is hard and then you die...
Anyway, thank everybody for the help. I'll try the solutions you suggested.

**Comment by nabbestemmia** [comment]
I resolved this way:
I created this class

`class UntrustedCertificatesDelegate: NSObject, URLSessionDelegate{
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust{
            let credential = URLCredential(trust: challenge.protectionSpace.serverTrust!)
            completionHandler(.useCredential, credential)
        }
    }
}`

and then used it like this:

`let delegate = UntrustedCertificatesDelegate()
let ns = URLSession(configuration: conf, delegate: delegate, delegateQueue: nil)        
super.init(baseURL: testUrl, networking: ns)`
