### ISSUE TITLE
Support for HEAD verb

### ISSUE THREAD

**Issue by yesitsdave** [bustoutsolutions/siesta#200]
For a project I'm busy with, I need support for HEAD, and noticed that it is not implemented as far as I can see. 

Is there a reason for this? Would be happy to add it and submit a PR unless there is a good reason why it doesn't exist.

**Comment by pcantrell** [comment]
The good reason is … none at all.

I’d welcome a pull request! Some design questions:

1. What kind of entity should it return? `Entity<Data>` with zero-length data? Or `Entity<Void>` to help code not accidentally parse an empty response?

2. How does this interact with the transformer pipeline? Should Siesta take special measures to prevent transformers from operating on HEAD responses?

3. `Request` currently guarantees that any request that calls `onSuccess` will also call _exactly_ one of `onNewData` or `onNotModified`. I’d like to preserve that guarantee. Since a HEAD doesn’t actually return any data, `onNewData` seems like a bit of a misnomer — but I tend to think that we should interpret it as meaning “there _would be_ new data if you made a GET request,” and thus interpret HTTP response codes exactly as we do for the other methods. Thoughts on that?
