### ISSUE TITLE
Ability to send non-unique params 

### ISSUE THREAD

**Issue by sapieneptus** [bustoutsolutions/siesta#261]
Currently, using `.withParam()` with the same key multiple times will result in the keypair being overwritten and ending up with only one value for that key, e.g.
```
resource.withParam("key", "val1").withParam("key", "val2")
```
will produce `https://api.com?key=val2`

It seems there are web services out there that actually require duplicated keys in some GET requests, e.g. 
```
https://api.com?key=val1&key=val2
```
(I suppose as a way to represent an array). 

There is a workaround for this using `.withParam("key=val1&key=val2", "")` but then the query string gets percent encoded which also doesn't sit well with all APIs. 

If there's already a workaround to achieve this, would love to know!

**Comment by pcantrell** [comment]
Yes, `.withParam("key=val1&key=val2", "")` should definitely _not_ work, because part of that method’s contract is that it escapes as necessary to make sure the key is the key and the value is the value; if it does, it’s a bug.

The best current workaround is to construct the query string yourself. You can use `Resource.relative(…)` to provide your own entire query string while still relying on Siesta to construct the rest of the URL:

```swift
resource.relative("?key=val1&key=val2")
```

Note that:
- this replaces the _entire_ query string, overriding any previous `withParam` calls, and
- you are responsible for doing the escaping yourself.

My sense is that APIs that use multi-valued keys are rare enough these days that deeper support isn’t necessary, but I’d certainly change my mind about that in the face of evidence to the contrary.

**Comment by sapieneptus** [comment]
> `resource.relative()`

Seems to do the trick! Not the prettiest thing in the world, but far better than monkey patching to make `Request#url` writeable or swizzling `#withParam()`.

> APIs that use multi-valued keys are rare

Agreed, I just happen to be working with one :) I'll close this issue as the workaround is sufficient, thanks!

**Comment by pcantrell** [comment]
Sounds good. Feel free to reopen (sapieneptus or others) if this is a widespread probelm.

> monkey patching to make Request#url writeable

Definitely don’t do that. Making `Request` mutable would break all kinds of critical assumptions.

> swizzling #withParam()

Or better yet, you could write an `extension Resource { func addParam(…) }` that appends a param to the query string without replacing existing ones. That might suit your needs in a tidy way.
