### ISSUE TITLE
RemoteImageView placeholderImage not showing when imageResource or ImageURL is nil

### ISSUE THREAD

**Issue by Dreadrik** [bustoutsolutions/siesta#288]
The RemoteImageView placeholder image is not showing when imageURL (and indirectly imageResource) is set to nil. I'm not sure if this is intentional or not.

The problem lies on this line in RemoteImageView:updateViews():

` image = imageTransform(imageResource?.typedContent(ifNone: placeholderImage))`

It should probably look something like this:

`image = imageTransform(imageResource?.typedContent() ?? placeholderImage)`

**Comment by pcantrell** [comment]
This is intentional. A nil image means “nothing is supposed to be here;” the placeholder image means “something is _supposed_ to be here, but is currently not available.”

A hack to work around this behavior: instead of setting the image to nil, do this:

```swift
foo.imageResource = foo.imageService.resource(absoluteURL: nil)
```

This creates a resource that always fails, and thus always shows the placeholder.

**Comment by Dreadrik** [comment]
Cool. I'm satisfied with this!
