### ISSUE TITLE
Proposal: More elegant way to avoid memory leak in closures

### ISSUE THREAD

**Issue by romansavrulin** [bustoutsolutions/siesta#292]
Hello, 

You're advising to use `[weak self]` to avoid retain cycles in closures. Don't you mind to take a look [at the following API solution](https://medium.com/anysuggestion/preventing-memory-leaks-with-swift-compile-time-safety-49b845df4dc6)? The main reason I'm proposing this is (quote)

```text
We can’t rely even on ourselves to write [weak self] in every part of our app (where needed),
and we certainly cannot expect all our potential API users to do the same. 
As API designers, we need to care about safety at the point of use.
```

**Comment by pcantrell** [comment]
Yes, Siesta has exactly this in the form of the [`ResourceObserver`](https://bustoutsolutions.github.io/siesta/api/Protocols/ResourceObserver.html) protocol, and the problem you mention is precisely why [the README suggests using the delegate pattern first](https://bustoutsolutions.github.io/siesta/#basic-usage).

**Comment by romansavrulin** [comment]
@pcantrell 

That's nice! I've overlooked that it has been implemented for observers. Will this also work for configurations and request handlers? Can you tell if it is safe to use self in this scenarios (and why)? Wouldn't be there a memory leak then in case API object is destroyed?

```swift
service.configure("**") {
            if let session = self.appSession {
                $0.headers["Authorization"] = "Bearer \(session.tokens.access)"
            }
        }
```

and

```swift
func startSession(_ uuid: String) -> Request {
        return sessions.request(.post, json: ["status": SessionState.connecting.rawValue, "uuid_d": uuid]).onSuccess(
            { data in
                
                log.info("Session created with \(data.content)")
                
                guard let session:SessionResponse = data.typedContent() else {
                    log.info("unable to get Session data!")
                    return
                }
                self.currentSessionStorage = session
                
                self.sessions.child(String(session.session.id)).overrideLocalContent(with: session)
            })
    }
```

**Comment by pcantrell** [comment]
These are good questions.

`onSuccess` and friends do not generally pose the risk of a retain cycle, because the request releases its callbacks once they’ve been called. This means that there is a retain cycle while the request is in progress, but the cycle breaks when the request complete.

Configuration blocks can indeed create retain cycles. There are several reasons why there is no delegate option for them:
- Most `Service` instances are either explicitly singletons, or live as long as the app’s process. Creating and re-creating multiple service instances for the same API is usually a sign of some kind of design mistake.
- In practical usage, the majority of configuration closures capture local variables but not `self`.
- Most importantly, the delegate pattern would make Siesta config verbose to the point of illegibility. Services typically have dozens of small configuration closures. With the delegate pattern, every one would need to be a separate type with its own name, ivars, etc.

**Comment by romansavrulin** [comment]
Thank you for your explanation. I was not sure about if escape closures of Request is deleted after processing.

We use API object as singleton, so no need to destroy it, actually. This was kinda "just curious" question.
