### ISSUE TITLE
addObserver with Closure -  Type of Expression is ambiguous without more context

### ISSUE THREAD

**Issue by andrewloyola** [bustoutsolutions/siesta#34]
I'm working on a Proof-of-Concept using Siesta, and am fairly new to Swift coming from Objective-C so please forgive if this is a basic question.  

I'm following the model Transform example in the README, trying to use a the model object with typedContent()  in my closure, but i keep seeing the "ambiguous without more context error"

here is the closure in viewDidLoad()

            API.resource("/profile/").addObserver(self) {
                [weak self] in
                self?.refreshText($0.typedContent()) //"Type of expression is ambiguous without more context"
            }

and refreshText is simple

           func refreshText(user: MiniUser){
             self.txtView.text = user.fullName
          }

this seems like it should work in a straightforward way, any ideas on what might be wrong with this?  ~~it seems to work if i make the ViewController a ResourceObserver and use the delegate call instead, but the closure has been problematic.~~ edited: this does not work either, it gives a similar "ambiguous" error

**Comment by andrewloyola** [comment]
a bit more detail, the delegate version works with the following:

    func resourceChanged(resource: Resource, event: ResourceEvent) {
        if let content = resource.typedContent() as MiniUser? {
            refreshText(content)
        }   
    }

but i'm having some trouble still with the closure version.  My understanding from the example is that it should infer the type of typedContext(), so there shouldn't be any ambiguity.

**Comment by pcantrell** [comment]
Ah, two things: first, there’s a mistake in the README. That’s what I get for editing in place without testing! It should read like this:

        API.resource("/profile/").addObserver(self) {
            [weak self] resource, _ in
            self?.refreshText(resource.typedContent())
        }

I think the problem here is that Swift doesn’t know whether $0 means just the first arg, `resource`, or the whole `(resource,event)` tuple. Which is dumb, and I wish they’d fix it. Hmm. Something for the swift-evolution list…. Anyway, code above should fix it, and I'll fix the README when I get a chance.

Second thing is that `refreshText` needs to accept an optional arg, because there’s no guarantee that you actually got a `MiniUser`:

      func refreshText(user: MiniUser?){
         self.txtView.text = user?.fullName
      }

Alternatively, you could test this in the closure (warning: more untested code here!):

        API.resource("/profile/").addObserver(self) {
            [weak self] resource, _ in
            if let user: MiniUser = resource.typedContent() {
                self?.refreshText(user)
            }
        }

      func refreshText(user: MiniUser){
         self.txtView.text = user.fullName
      }

…although you’ll probably want to update the UI for a “no user” state as well, so usually it makes more sense for `refreshText` to accept the optional and either update or clear the UI.

Let me know if that does the trick!

**Comment by andrewloyola** [comment]
👍 thanks @pcantrell that  worked well! (I went with the alternative version with the unwrap in the closure)

the only thing different from your untested version was that that XCode makes me add owner to addObserver, like this:

            OFLAPI.resource("/v0.1/profile/").addObserver(owner: self) { ... }

**Comment by pcantrell** [comment]
Fixed the README. Thanks for the heads up!

One of these days, I’ll get around to writing a script to copy all those code snippets in the docs out of a project that makes sure they actually compile. Hard to keep them up to date as the API stabilizes for 1.0.
