### ISSUE TITLE
Service.addObserver(owner: closure:) Allows multiple observers for self

### ISSUE THREAD

**Issue by MPiccinato** [bustoutsolutions/siesta#36]
I was doing some testing of grabbing a resource, adding an observer and calling load in viewDidAppear. Within the closure I would print the 'event' and noticed after multiple calls to viewDidAppear the print statement was being called multiple times per an event.

```swift

override func viewDidAppear(animated: Bool) {
    super.viewDidAppear(animated)

    MyAPI.resource('/home').addObserver(owner: self, closure: {
        [weak self] resource, event in
        print(event)
    }   
}
```

I dug around a bit and it appears that it might just be an issue with the ClosureObserver.

**Comment by pcantrell** [comment]
The problem is that Swift has no notion of closure identity or comparison: there’s no way for Siesta to know that you’re adding “the same” closure twice, because there’s no such thing as “the same” closure.

If you add an observer that’s an object, then Siesta will prevent dups. But otherwise, it’s up to you to make sure you don’t add redundant observers — by adding them in `viewDidLoad` instead of `viewWillAppear`, for example.

**Comment by pcantrell** [comment]
Prompted by this, I added [some information about duplicate observers](https://bustoutsolutions.github.io/siesta/api/Classes/Resource.html#/s:FC6Siesta8Resource11addObserverFS0_FT5ownerPSs9AnyObject_7closureFT8resourceS0_5eventOS_13ResourceEvent_T__DS0_) to the API docs. Thanks for the good question!

Also, an aside on the code you posted: in Swift, when the last arg is a closure, you can place it as a block after the method call. So instead of this:

    MyAPI.resource('/home').addObserver(owner: self, closure: {
        [weak self] resource, event in
        print(event)
    })

…you can do this:

    MyAPI.resource('/home').addObserver(owner: self) {
        [weak self] resource, event in
        print(event)
    }

You may already know that, but I though I’d mention it just in case.

**Comment by MPiccinato** [comment]
That makes a lot of sense with Swift. I guess from the API of a Siesta Service class I made an assumption that 'self' would be the qualifier for adding an extra observer to that resource. Is there a use case to adding multiple 'self' owners to a specific resource?

**Comment by pcantrell** [comment]
The owners are about lifecycle, not uniqueness. When the owner goes away, the observer stops observing. When you want to remove observers, you do it by owner. There’s a [detailed explanation in the docs](http://bustoutsolutions.github.io/siesta/guide/memory/).

> Is there a use case to adding multiple 'self' owners to a specific resource?

Observers have owners, not resources, so I’m not quite sure what you mean by that. I’m guessing you mean, “Is there a use case for having multiple observers with the same owner?,” then sure; in fact, it’s quite common. For example, a view controller might might do this:

    foo.addObserver(self)
    bar.addObserver(self)
    bar.addObserver(owner: self) {
        [weak barDisplayerWidget] in
        barDisplayerWidget?.refresh()
    }

Here, the VC depends on two resources, so it observes both of them (as a self-owned observer). It also owns a `barDisplayerWidget` that wants to observer the second resource. All three observers are owned by `self`, so when the VC is deallocated, Siesta automatically stops sending events to all of them.

This also has the advantage that you can remove multiple observers at once:

    for resource in [foo, bar] {
        resource.removeObservers(ownedBy: self)
    }

…which is a common idiom when one VC wants to change which resource it’s observing. There’s an [example of this](https://github.com/bustoutsolutions/siesta/blob/master/Examples/GithubBrowser/Source/UI/RepositoryListViewController.swift#L14-L22) in the sample project.

**Comment by MPiccinato** [comment]
I understand now with that example. My pattern was to only have one observer per a resource per a controller. Having multiple closures available I can see being helpful. I will switch to using the just addObserver(self) for my current case and implementing ResourceObserver protocol.
