### ISSUE TITLE
Adding persistent data store to Siesta

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#59]
I'm looking at using Siesta in an app where one of the major use cases is that the user can download content for offline use, and otherwise have a decent experience in the app offline or with a dodgy network.  I have a dream for this app!

In my dream, the model layer would be oblivious to network conditions and would receive either live data or stored data (with live updates, if they become available).  Would it make sense to add some kind of support for a persistent data store in Siesta, or is that better handled in a wrapper around Siesta?  I'm in my initial design phase; any pointers you can give me would be appreciated.

**Comment by pcantrell** [comment]
Siesta provides an interface but not an implementation for this.

This is exactly what `EntityCache` is for, and it does basically what you describe but one better: the model layer immediately gets the cached data (if any), and then gets a “new data” notification if a network call succeeds. In the offline state, you’ll see both the cached _and_ the “no connection” error on the Siesta resource. Your UI can decide for itself what to do with that — for example, it could show the “no internet connection” error in a little banner at the top, then show the cached data underneath.

Alas, `EntityCache` is only a protocol for now. I plan on providing a public `EntityCache` implementation baked into Siesta, but I want to get the API changes in #32 vetted and released first, because the protocol will likely change when it’s done.
