### ISSUE TITLE
Reactive extensions / examples

### ISSUE THREAD

**Issue by istvanelekes** [bustoutsolutions/siesta#6]
Do you have support for Rx, or I misunderstand the observer logic?

**Comment by pcantrell** [comment]
There’s no built-in extension for any particular reactive framework, though certainly Siesta’s architecture would fit quite naturally into a reactive project. Siesta’s built-in observer logic is sort of “reactive lite,” and gives some of the code-simplifying benefits of reactive programming without having to go fully Rx.

I’d _love_ to add extensions for ReactiveCocoa and RxSwift to Siesta, either as examples in the docs or as optional plugins. Send a PR or a gist!

**Comment by piv199** [comment]
If there any updates? I would like to use ReactiveCocoa with Siesta!

**Comment by akaralar** [comment]
reactivecocoa support would be amazing

**Comment by pcantrell** [comment]
I’m not actively working on it — my priority is stabilizing the API so we can cut a 1.0 release — but this is “help wanted” issue so I’d welcome a PR!

If anybody gets a plugin working and wants to submit it:

- Put the plugin code in `Extensions/ReactiveCocoa`.
- Add your code to the iOS & macOS  **test** targets in Xcode (but not the core project targets).
- Add ReactiveCocoa to `Cartfile.private`.
- Write specs.
- Add a new subspec to `Siesta.podspec`. (You can use the Alamofire one as an example.)

**Comment by akaralar** [comment]
I'm thinking about how this could be implemented, shall we need to return a hot signal for `addObserver` methods? what happens with `request` methods and one time hooks? Also resources can be released in cases of memory pressure, what happens to hot signals then? 

What are the cases that need to be handled at minimum for this to work properly?

**Comment by pcantrell** [comment]
Here are some quick initial thoughts, which are probably have wrong so take them with a grain of salt:

- Resources and requests should both be signal producers. They handle two different cases: one for when you want the latest data wherever it came from, and the other for observing a specific request.
- Resource signals use addObserver. Request signals use onCompletion.
- Resources only get released if nobody is using them. An active signal should retain a resource as long as it has subscribers … however that works in ReactiveCocoa.

**Comment by VDKA** [comment]
For RxSwift

```swift
import Siesta
import RxSwift

extension Request {

  var rx_success: Observable<Bool> {

    return Observable.create { o in

      self.onCompletion { response in

        switch response {
        case .Success(_):
          o.onNext(true)

        case .Failure(_):
          o.onNext(false)
        }
        o.onCompleted()
      }
      return AnonymousDisposable { self.cancel() }
    }
  }

  var rx_response: Observable<Siesta.Response> {

    return Observable.create { o in

      self.onCompletion { response in
        o.onNext(response)
        o.onCompleted()
      }

      return AnonymousDisposable { self.cancel() }
    }
  }

  var rx_entity: Observable<Siesta.Entity> {

    return Observable.create { o in

      self.onCompletion { response in

        switch response {
        case .Success(let entity):
          o.onNext(entity)

        case .Failure(let error):
          o.onError(error)
        }
        o.onCompleted()
      }
      return AnonymousDisposable { self.cancel() }
    }
  }
}
```

**Comment by pcantrell** [comment]
Thanks for this, @VDKA! Is it similarly easy to make an extension for `Resource`? I feel like that's where the real reactive payoff would be — but I don’t know enough about the lifecycle of an `Observable` to know whether it would cause a `Resource` to be retained longer than it ought to be.

**Comment by akaralar** [comment]
@pcantrell I'm thinking about implementing at least some `RAC` wrapper for the library, but there is one issue I'm not certain about. In RAC a signal is terminated when an error event occurs, however the ephemeral nature of the library requires the subscription to continue even if there is an error. I can think of a few ways to overcome this:
 
- Do away with RAC error handling mechanism and send the `Resource` and `ResourceEvent` parameters as `next:` values, even though there may be some error.
- Have a signal of signals that converts each `resourceChanged()` calls to signals that need to be subscribed by the observer each time, and if the event in the inner signal is an error, then forward it to `error:` instead of `next:`.
- Make `latestData`, `latestError`, and `isLoading` seperate signals and handle each in separate blocks.
- ...?

If I can find a neat way to implement the bindings, this will be my first open source contribution so please feel free to nurture me with criticism. :)

**Comment by pcantrell** [comment]
@akaralar: I’d happily welcome a PR for this, and would be very happy to guide you through any Siesta-related points of uncertainty! Once you have some code worth sharing, even if it’s incomplete, put your work on a `reactivecocoa` branch in your own fork of the project and go ahead and open a pull request off that branch.

The solution to the error problem is clear. (Or at least I _think_ it’s clear, which means I probably don’t understand it. Beware the obvious!)

A resource-centric signal would take a snapshot of the several `Resource` properties that change over time, and publish that snapshot. Here’s a sketch:

```
public struct ResourceState  // Crucial that it is a struct!
    {
    public var data: Entity?
    public var error: Error?
    public var isLoading, isRequesting: Bool
    }

public extension Resource
    {
    var state: ResourceState
        {
        return ResourceState(
            data: latestData,
            error: latestError,
            isLoading: isLoading,
            isRequesting: isRequesting)
        }
    }
```

A signal attached to a resource would expose only that `ResourceState` struct — not the resource itself. (The struct is immutable & threadsafe, or at least as threadsafe as the entity’s content. A `Resource` is neither immutable nor threadsafe.)

It’s probably smart to attach the content convenience accessors to that, so that you have `typedContent()`:

```
extension ResourceState: TypedContentAccessors
    {
    public var entityForTypedContentAccessors: Entity?
        { return data }
    }
```

Or better yet — and here I’m going out on a limb — the standalone `ResourceState` struct avoids the limitations of Swift that prevented Siesta from having a fully generic `Resource<T>`, so you could _probably_ make this work:

```
public struct ResourceState<T>
    {
    public var content: T?
    public var error: Error?
    public var isLoading, isRequesting: Bool
    }

public extension Resource
    {
    func stateSnapshot<T>() -> ResourceState<T>
        {
        let data: T? = latestData?.typedContent()
        let contentTypeError: Error? =
            (latestData != nil && data == nil)
                ? Siesta.Error(
                    userMessage: "The server return an unexpected response type",
                    cause: Error.Cause.WrongContentType())
                : nil
        
        return ResourceState(
            content: nil,
            error: latestError ?? contentTypeError,
            isLoading: isLoading,
            isRequesting: isRequesting)
        }
    }

extension Siesta.Error.Cause
    {
    public struct WrongContentType: ErrorType { }
    }
```

Too much of a brain dump? Let me know if that makes sense.

**Comment by akaralar** [comment]
@pcantrell Thanks for the detailed explanation! Yeah that makes sense. Great food for thought :) Let me see if I can get something working and send a PR.

**Comment by pcantrell** [comment]
Closing this thanks to @akaralar’s contribution — but I’d gladly welcome an RxSwift extension as well.

**Comment by hherman1** [comment]
PAUL!
