### ISSUE TITLE
issue with post

### ISSUE THREAD

**Issue by awclives** [bustoutsolutions/siesta#68]
Greetings,

The siesta framework code below does not work, but the Alamofire code does work.  My server sends back a 400 for the request sent by siesta.  I would expect these to do the same thing, but perhaps I am missing something:
```
		HighlightAPI.sync().request(.POST, json: dictionary as! NSDictionary)
        
        Alamofire.request(.POST, "http://localhost:8080/api/private-highlights/sync", parameters: dictionary, encoding: .JSON)
```

where HighlightAPI.sync() returns the same url as in the Alamofire call.

**Comment by pcantrell** [comment]
This isn’t much information to go on. The `as! NSDictionary` is curious; you shouldn’t need that. Otherwise, there’s nothing obviously wrong with what you’re doing.

The way to diagnose this problem is to ask Siesta to tell you exactly what request it’s sending, and make sure it’s the request you mean to be sending:

```
Siesta.enabledLogCategories = [.Network, .NetworkDetails, .ResponseProcessing]
```

…or for the full firehose:

```
Siesta.enabledLogCategories = LogCategory.all
```

I’m marking this closed since it’s not (yet) an issue with Siesta, but please feel free to keep commenting on this issue for help. And please do file an issue if you do find something that’s a specific bug, shortcoming, or feature request!
