### ISSUE TITLE
Allow structured EntityCache keys

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#89]
I have hierarchical data which I am requesting using Siesta.  My API is designed so I can make requests at each level of the hierarchy.  They are journals which contain issues, which then contain articles.  So, if I use Siesta to request an issue, I get a list of articles in my response.  My understanding is that an implementation of EntityCache at the model stage would see this as a request to store an array of models, with the url as the key (I assume that's what would be in `EntityCacheKey`, although I also assume I'm not supposed to rely on it).  In my app, a user can choose one article to store and use (potentially offline) later.  So, when that request comes in, the url would be for a single article, not the issue that the article was originally requested in.  Since I'm not suppose to parse the `EntityCacheKey`, I'd have no way of knowing this in my `EntityCache` implementation, nor do I really want to have url parsing bolted onto that cache.  

The thing that comes to mind to me is that I would want to be able to transform the `EntityCacheKey` into an array of keys just before we write to the cache (the issue url and all the article urls).  It might be handy at that point to convert from urls to a key type I can specify, so my cache isn't in the business of parsing urls.  Then I can store each article in my cache as a separate entity.  Then, when it's time to query the database, we can use a related conversion process, and the cache can lookup by an array of keys, which in the example I've laid out would be just one key (the article).  There are other cases where I want to lookup an arbitrary list of articles.

What would you think @pcantrell?  Do you have a different way to do this?

**Comment by pcantrell** [comment]
The reason the cache keys are opaque is that I want to leave room for Siesta to include more than just the URL in the cache key in the future. For example, you might want to make it a digest of (URL + secure auth token) so that you can securely cache data for multiple users on one device.

> So, when that request comes in, the url would be for a single article, not the issue that the article was originally requested in.

This is a sticky situation. The one-to-one relationship between URLs and resources is baked pretty deeply into the cache, so storing something with one key and retrieving it with another certainly does break the mold.

I pondered making each `EntityCache` responsible for generating its own keys. Doing that gets complicated, but you make a compelling case for it:

> I would want to be able to transform the EntityCacheKey into an array of keys just before we write to the cache (the issue url and all the article urls). It might be handy at that point to convert from urls to a key type I can specify, so my cache isn't in the business of parsing urls.

I suspect many users would like to use a structured database as a cache store instead of the “raw bytes on disk” approach that the current API assumes. I’ll poke at this when I find some time, and when I do, I’ll call on you to try whatever I come up with and see if it makes sense.

**Comment by jordanpwood** [comment]
>The one-to-one relationship between URLs and resources is baked pretty deeply into the cache, so storing something with one key and retrieving it with another certainly does break the mold.

It seems like this could be implemented to be totally transparent to Siesta, since it would be the responsibility of the `EntityCache` implementor to take the url and the `Entity` in the pipeline (at whichever stage the persistent cache is working at), and output a key of their choice.  Then when it's time to do a lookup in the cache, the implementor has to be able to take the url and turn it into a key which can produce an entity with the correct value.  I'm confident that I could do that with my data and urls.  It doesn't matter to Siesta if the url being looked up was never actually seen, and its my understanding that it would then proceed after the persistent cache hit to actually request the url in question, which is fine by me.

I do have some related `EntitiyCache` questions which the documentation doesn't cover (and I haven't yet dug in the code to find the answer for myself 😅).  Is there support for staleness in the `EntityCache`?  Since you don't know when something went into the cache, I assume there's no general support for that.  But what happens when a known resource is cleared from the in memory cache?  Is the `EntityCache` informed?

**Comment by pcantrell** [comment]
Got inspired, and put up an implementation of this and #90 on the [`structured-cache-keys`](https://github.com/bustoutsolutions/siesta/tree/structured-cache-keys) branch. @jordanpwood, if you have a chance, give it a whirl!

**Comment by jordanpwood** [comment]
Let me start off by saying, Wow!  You got this code change out blazingly fast!!  I'm incredibly impressed.

To test things out, I've made a little sample app which loads a resource from our API, and have hooked up a pseudo persistent cache to it, just to check your new branch out.  

One possible bug I'm seeing is that the first time I call `loadIfNeeded`, I'm seeing a cache request for each of the resources in the path to the fully constructed URL.  What I mean is, I'm creating the resource like so:

``` 
func articleInPressPageResource(journalId: String, cursor: String?) -> Resource {
        return libraryResource
            .child(Endpoint.journals.rawValue)
            .child(journalId)
            .child(Endpoint.aip.rawValue)
            .withParam(QueryParameter.cursor.rawValue, cursor)
    }
```

And for every call to `child`, I'm seeing a key get created and a call to `readEntity`.  After that initial setup, everything behaves as I expect.

As to the behavior of `wipe`, I would say that I would expect Siesta to be generally in charge of the current state of caching, so when it gets a call to `wipe` it would pass that onto the persistent cache.  However, Siesta wouldn't know the full extent of which data should be purged, so maybe that wouldn't be good idea.  For my API, I can't really use an auth token as part of the persistent store, since they expire if they aren't used frequently enough.  So the same user can be authenticated with the same permissions, and have a different auth token.  I suppose I could update the cache when I get a new token... I'd love to hear any advice you have on the topic.

In general, I give a big 👍 to the cache key, it works just the way I would expect it to.

**Comment by pcantrell** [comment]
Thanks for kicking the tires! Having passed your sanity check, I’ll promote it to a PR to encourage further review.

The thing where you see cache misses for each `child()` and `withParam()` step bugs me too, and is on my list. The problem is that right now, resources try to load their content from the cache as soon as they’re instantiated. I think instead that they should do it on the first read of `latestData` and/or the first call to `addObserver()`. Not sure whether first, second, or both would be least confusing. Hmm.

On `wipe()`, my thinking is starting to clarify a bit. For forcing a new request on the next resource load, there’s already `invalidate()`. The purpose of `wipe()` is not just to say “please remove the cache entry,” but rather to say “config or context has changed in a way that changes the _meaning_ of the load request” — with change of auth being the primary example. To that end, `wipe()` not only does not remove the entity from the EntityCache, but initiates a new cache load _after_ the resource is wiped. I think that’s right. It’s up to you to make sure that your cache takes into account the same things that would change what the server returns, and if you’re not doing that properly, you’d be clued into the problem when you see the same data immediately pop back out of the cache after a wipe. This is all clear in my head, but I’m not sure it’s making sense as I type it out.

---

> For my API, I can't really use an auth token as part of the persistent store, since they expire if they aren't used frequently enough.

Yeah. If you want to support caching on a single device, _and_ you want to protect one user from being able to view another’s cached content, then the options I see are:

- include some secure digest of the login as part of the cache key (e.g. bcrypt(login+password)), or
- have the server provide a randomly generated encryption key, perhaps tied to the specific device, that remains the same over longer periods of time.

I used the latter approach on a project once, and it worked nicely. On that project, though, offline access was not a requirement; if you want offline, only the first approach works (I think?). You lose your cache when your password changes, but oh well — it’s just a cache.
