### ISSUE TITLE
configureTransformer - Cannot invoke with an argument list

### ISSUE THREAD

**Issue by shaneneuerburg** [bustoutsolutions/siesta#9]
When trying to use configureTransformer as follows:

```
configureTransformer("/foo") { String($0) }
```

I get the following error: 
> Cannot invoke 'configureTransformer' with an argument list of type '(String, (_) -> _)'

From the documentation in the code, this seems like it should work. However, I'm not enough of a Swift expert to figure out what exactly that chunk of code is expecting :)

**Comment by pcantrell** [comment]
Hmm, the docs may be out of sync a bit with where the API ended up for beta 3.

Let me know what happens if you do this:

    configureTransformer("/foo") { String($0.content) }

**Comment by pcantrell** [comment]
OK, too hasty trying to answer questions on the go. Here’s a more careful — and actually tested! — answer:

If you expect the response content to already have been transformed into a `String` by the earlier transformers in the pipeline, then do this:

    service().configureTransformer("/foo") { $0.content as String }  // example 0

This doesn’t transform the content, but it does make cause Siesta to report it as an error if the content comes out as anything other than a string.

If you are getting something else from the transformers, an `Int` for example, and you want to convert it into a string, do this:

    service().configureTransformer("/foo") { String($0.content as Int) }  // example 1

Or if you prefer a very explicit approach:

    service().configureTransformer("/foo") {  // example 2
        (content: Int, entity: Entity) -> String in
        String(content)
    }

Example 2 is what the Swift compiler infers from example 1, all spelled out. Those two are equivalent.

The underlying principle to all of this is that `configureTransformer(...)` uses Swift’s type inference to determine your transformer’s input and output type. That means that your closure needs to make it clear to the compiler exactly what types it expects, resulting in two common confusions:

1. If you just use a bare `$0` in your transformer closure, Swift doesn’t know whether you mean the `content` argument, or the entire `(content,entity)` tuple. Usually Swift can infer which one you mean, but because `configureTransformer(...)`’s first argument is a generic type, there’s not enough information in this case. Saying `$0.content` removes that ambiguity.
2. You need to make sure that `$0.content` can only have one possible type in the context where you use it, or the compiler can’t infer its type. There are many `String(_:)` initializers, so you need to pick one using the `as` clause. Similarly, you need to make sure your closure has an unambiguous return type.

**Comment by shaneneuerburg** [comment]
Awesome! That helps immensely.

Works great now! Thanks!

**Comment by pcantrell** [comment]
Glad it helped!

Please keep the issues coming. It’s really helpful to know how people are using Siesta, and where the stumbling blocks are.

**Comment by shaneneuerburg** [comment]
:+1:

**Comment by gthrb22** [comment]
How to map the model for the response string
