### ISSUE TITLE
Add ability to specify which background queue to use for EntityCache

### ISSUE THREAD

**Issue by jordanpwood** [bustoutsolutions/siesta#90]
In the `EntityCache` docs, it says:
>Siesta calls `EntityCache` methods on a GCD background queue

My implementation of EntityCache must run on a serial dispatch queue I setup, and rather than making a whole bunch of calls to `dispatch_sync`, I'd like to just tell Siesta which queue it is, and have my `EntityCache` methods execute on that queue.

**Comment by pcantrell** [comment]
Hmm, the calls to `dispatch_sync` are what I’d imagined people would do in your situation. (It’s only three calls for the three required methods of `EntityCache` — or four, if you want to write a custom `updateEntityTimestamp`.) I’d hesitated to muddy the waters with this, and in theory, the overhead of `dispatch_sync` should be negligible. In theory.

In practice, since you’re the second person to ask for this, seems like it’s a reasonable thing to add.

**Comment by jordanpwood** [comment]
This is definitely a "nice to have" level feature, I'll let you know if I find any performance issues related to this.
