### ISSUE TITLE
Variable Urls for multiple microservices

### ISSUE THREAD

**Issue by Reedyuk** [bustoutsolutions/siesta#91]
Hi,
I'm in a tricky situation with my code base, im not sure whats the best approach. 
We have a project where, we are using multiple microservices, in production they exist like this:
https://cool.com/user-service/
https://cool.com/cool-service/
And in the swift code, i have one instance of webservice which has the base url set as https://cool.com, then i have "service" classes which add to the path, e.g. UserService.swift would have "/user-service".
But when we operate locally, because our services are all microservices, they are actually operating on
http://localhost:8081/
http://localhost:8082/
I'm wonder what the best practice is from the Siesta team, with dealing with this. I dont want to have a separate instance of the web service object for every service. I also dont want to have to put in the full path url when making a request for every request.
Thoughts and suggestions? 

Thanks
Andrew.

**Comment by Reedyuk** [comment]
At the moment im using a preprocessor macro to handle the switch between the base url overall. e.g. https://cool.com and http://localhost, but that doesnt fix the issue with ports etc.

**Comment by pcantrell** [comment]
You can create a service without a `baseURL`. See [this comment](https://github.com/bustoutsolutions/siesta/issues/84#issuecomment-236208734) for more info.

I’d recommend doing that, then providing a convience method for each microservice:

```swift
final func coolResource(path: String) -> Resource {
    return resource(absoluteURL: coolBaseURL).child(path)
}

final func userResource(path: String) -> Resource {
    return resource(absoluteURL: userBaseURL).child(path)
}
```

Then you can set up `coolBaseURL` and `userBaseURL` however you like.

You’ll lose the nice thing Siesta does to prevent redundant leading slashes; that is, you’ll need to decide either to put a trailing slash on `coolBaseURL` _or_ a leading slash on `path`, but not both. Otherwise, this will work exactly like `baseURL`.

Hmm, you know, it would be nice for Siesta to provide `Service.resource(baseURL:path:)` as a convenience. I’ll keep this issue open as a reminder to add that.

> I dont want to have a separate instance of the web service object for every service.

If the microservices link to each other, then yes, you want just one service to guarantee resource uniqueness. (That is, if you use `Resource.relative()` to traverse from https://cool.com/cool-service/xyz to https://cool.com/user-service/users/1, then you’d need a single service instance to ensure that you have a single resource for /users/1.)

Otherwise, there’s no problem with having multiple ones. `Service` doesn’t have a particularly large per-instance overhead.

**Comment by Reedyuk** [comment]
ok, sounds good. Thanks
