### ISSUE TITLE
Error when trying siesta with Argo

### ISSUE THREAD

**Issue by onekiloparsec** [bustoutsolutions/siesta#93]
Hi Paul, 

I'm diving even deeper into siesta, and I try to make it work with [Argo](https://github.com/thoughtbot/Argo). But I get an error I couldn't work around. That's maybe not an issue, but merely my own failure to grasp all the details involved here, especially with the siesta blocks arguments.

Here is the code, in my subclass of `Service`:

```
    public init(withAPIVersion version: String = "1") {
        self.APIVersion = version
        super.init(baseURL: "http://api.arcsecond.io")
        
        self.configureTransformer("/\(self.APIVersion)/objects/*") {
            decode($0.content) as AstronomicalObject
        }
    }
```
I get the following at the line `self.configureTransformer...`: 
>  Cannot invoke 'configureTransformer' with an argument list of type '(String, (_) -> _)'

The code for `AstronomicalObject` follows the exact same example given by Argo, in its simplest form:

```
public struct AstronomicalObject {
    public let name: String
}

public extension AstronomicalObject: Decodable {
    public static func decode(json: JSON) -> Decoded<AstronomicalObject> {
        return curry(AstronomicalObject.init)
            <^> json <| "name"
    }
}
```

I don't get this error when writing a "normal" init method for my struct, taking the `json` as parameter and doing all the parsing myself. But my goal is to use Argo precisely for that.

Any idea? Thanks in advance!

**Comment by pcantrell** [comment]
Ah, Swift type inference. It’s awesome … until it can’t figure something out.

I’m not familiar with Argo, but I’m guessing the problem is that its global `decode(_:)` method takes a type that is too broad for Swift to infer the input type of your transformer closure.

In these situations, my usual approach is to add explicit types until it works (or I get a more meaningful compile error), then trying removing them one by one to see which the compiler can infer. So maybe try something like this:

```swift
self.configureTransformer("/\(self.APIVersion)/objects/*") {
    decode($0.content as NSJSONConvertible) as AstronomicalObject
}
```

…or even the fully explicit version:

```swift
self.configureTransformer("/\(self.APIVersion)/objects/*") {
    (content: NSJSONConvertible, entity: Entity) -> AstronomicalObject
    return decode($0.content)
}
```

(Or should the content be `JSON` already? Not sure what Argo expects.)

This still may not work, but hopefully you’ll at least get a more helpful compiler error.

**Comment by pcantrell** [comment]
@onekiloparsec Did you ever get this working? If you did, let me know and we can find a place to drop an Argo example in the docs and/or `Extensions/`.

**Comment by onekiloparsec** [comment]
@pcantrell Sorry for the delay. The short answer is no. But I wanted to make a detailed answer after investigating a bit more.

**Comment by onekiloparsec** [comment]
Still struggling... I've updated to beta10, but I have an error message (also present with beta 8): 

`/Users/onekiloparsec/apps/arcsecond.swift/arcsecond/Arcsecond.swift:31:14: Cannot invoke 'configureTransformer' with an argument list of type '(String, () -> ())'`

For some reason, subclassing `Service` and calling in the `init` method:
`        self.configureTransformer("/\(self.APIVersion)/objects/*") {
            //
        }
`

produces this error (whatever I put in place of the `//`). Sorry for the trouble. I've re-read the documentation again, but I am probably missing something here.

The message says further more:
`/Users/onekiloparsec/apps/arcsecond.swift/arcsecond/Arcsecond.swift:31:14: Expected an argument list of type '(ConfigurationPatternConvertible, requestMethods: [RequestMethod]?, atStage: PipelineStageKey, action: PipelineStage.MutationAction, onInputTypeMismatch: InputTypeMismatchAction, transformErrors: Bool, description: String?, contentTransform: (content: I, entity: Entity) throws -> O?)'`

**Comment by pcantrell** [comment]
Down a Swift type rabbit hole!

I’ll have a chance to dig into this later this week. It certainly deserves attention — you won't be the last to hit it. If in the meantime you have time to prepare a minimal example project to reproduce the problem, that would be quite helpful.

**Comment by onekiloparsec** [comment]
Sure. here it is: [SiestaSwiftTypeRabbitHole.zip](https://github.com/bustoutsolutions/siesta/files/455990/SiestaSwiftTypeRabbitHole.zip)

**Comment by pcantrell** [comment]
OK, digging into this…

This doesn’t work because the trailing closure doesn’t use any inputs and doesn’t return anything, so Swift can neither infer the input nor the output type of your transformer:

    configureTransformer("/\(APIVersion)/objects/*") {
      //
    }

Back to your original Argo example, there was clearly some problem going on where both Siesta and Argo’s use of generic left Swift unable to figure out what set of types would make the whole closure compile. I therefore tried isolating just the Argo call, like this:

    let content = NSData()
    let x: AstronomicalObject = decode(content)

…which gave a much more helpful compile error: `decode(…)` returns an optional. Aha! Armed with that knowledge, I tried this, which compiles:

    configureTransformer("/\(APIVersion)/objects/*") {
        decode($0.content as NSData) as AstronomicalObject?
    }

This version, which is more verbose but perhaps clearer about the structure of things, also compiles:

    configureTransformer("/\(APIVersion)/objects/*") {
        (content: NSData, _) -> AstronomicalObject? in
        decode(content)
    }

I only verified compilation here, not correct behavior. Let me know if this unties the type knot for you!

**Comment by onekiloparsec** [comment]
Thanks a lot for your insightful help. It compiles indeed. But somehow, I couldn't get anything out of it anymore. I mean, when I have the `configureTransformer` call uncommented, not only it is never called (hence `decode` is never called), but the resource observer closure isn't called either! Am I missing something?

**Comment by onekiloparsec** [comment]
Even stranger, whatever the presence of a custom transformer or not, the following makes my Xcode editor crashes:

        self.hd5980 = self.arcsecond.object("HD 5980")
        self.hd5980!.addObserver(owner: self) { (resource, event) in
            print("resource \(resource.typedContent())")
        }

where the `object` func is defined like this in the `Service` subclass:

    public func object(name: String) -> Resource {
        return self.resource("/\(self.APIVersion)/objects/\(name)")
    }

**Comment by pcantrell** [comment]
> the resource observer closure isn't called either

This is a sign of something more that just `contentTransformer` trouble. Turn on the [detailed logging](http://bustoutsolutions.github.io/siesta/guide/logging/) and work through that line by line. It’s a little hard to wade through, but it will tell you exactly what’s going wrong.

    self.hd5980!.addObserver(owner: self) { (resource, event) in
        print("resource \(resource.typedContent())")
    }

Obviously the editor shouldn’t crash (!), but `typedContent()` will only work when its return type is constrained by its context. It means “conditional downcast to the type I expect.” That’s sort of the opposite of what you want; you’re looking for “just show me whatever type you have.” Try `latestData?.content` instead of `typedContent()`.

**Comment by onekiloparsec** [comment]
Thanks for the `typedContent()`, it's a misuse of mine.

As for the `contentTransformer`, I see "The network connection was lost". I have no clue how to fix it. Maybe with a different value of `keep-alive`, but still, I don't see why this suddenly stop working just because I'm using a transformer in my client code.

**Comment by onekiloparsec** [comment]
I am not so sure how I did fix that issue, but I did. It seems that increasing `TIMEOUT` value in my server from 30 to 60 did the trick, and I now have something that goes through the decoding of Argo! The only additional change was to set the type of `content` in the closure to `NSDictionary` rather than `NSData`. Thanks for your help!

**Comment by pcantrell** [comment]
Glad you worked it out! It _sounds_ like the network issue is outside of Siesta, but … at the very least, once the Swift 3 adventure is over, I'm keen to improve the readability of Siesta’s logging to help make these sorts of problems easier to diagnose.

> The only additional change was to set the type of content in the closure to NSDictionary rather than NSData

Sounds like Siesta’s default JSON parsing is still in the parsing. No harm in that, although depending on what Argo does under the covers, it might parse a snerch faster if you let it do the parsing to. (Or maybe Argo uses NSJSONSerialization too and it’s all the same!)
